# Generated by Django 4.1 on 2022-08-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='item',
        ),
    ]
