# Generated by Django 4.1 on 2022-08-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_name_post_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='location',
            new_name='market',
        ),
    ]
