# Generated by Django 4.1 on 2022-08-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(choices=[('강동구', '강동구'), ('강남구', '강남구')], default='강동구', max_length=100),
        ),
    ]
