# Generated by Django 4.1 on 2022-08-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_post_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='area',
            field=models.CharField(choices=[('서초구', '서초구'), ('은평구', '은평구'), ('노원구', '노원구'), ('마포구', '마포구'), ('광진구', '광진구'), ('금천구', '금천구'), ('양천구', '양천구'), ('동대문구', '동대문구'), ('강남구', '강남구'), ('성북구', '성북구'), ('중구', '중구'), ('강서구', '강서구'), ('송파구', '송파구'), ('관악구', '관악구'), ('종로구', '종로구'), ('서대문구', '서대문구'), ('도봉구', '도봉구'), ('강북구', '강북구'), ('성동구', '성동구'), ('구로구', '구로구'), ('동작구', '동작구'), ('중랑구', '중랑구'), ('영등포구', '영등포구'), ('강동구', '강동구')], default='노원구', max_length=100),
        ),
    ]
